all:
	gcc Sender.c -o Sender
	gcc Reciever.c -o Reciever

Sender: Sender.c
	gcc Sender.c -o Sender
	./Sender

Reciever: Reciever.c
	gcc Reciever.c -o Reciever
	./Reciever

clean:
	rm -f Sender Reciever
