all: 
	gcc Q1part1a.c -o Q1part1a
	gcc Q1part1b.c -o Q1part1b
	gcc Q1part2.c -o Q1part2

Q1part1a: Q1part1a.c
	gcc Q1part1a.c -o Q1part1a
	./Q1part1a

Q1part1b: Q1part1b.c
	gcc Q1part1b.c -o Q1part1b
	./Q1part1b

Q1part2: Q1part2.c
	gcc Q1part2.c -o Q1part2
	./Q1part2

clean:
	rm -f Q1part1a Q1part1b Q1part2